"""sqlite menyebalkan masalah datetime

Revision ID: 42a80eb24838
Revises: 1ec351e42e4b
Create Date: 2025-09-02 11:37:08.451614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a80eb24838'
down_revision: Union[str, Sequence[str], None] = '1ec351e42e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
